-- CreateEnum
CREATE TYPE "WebHackingMethod" AS ENUM ('XSS', 'SQL_INJECTION', 'CSRF', 'SSRF', 'DIRECTORY_TRAVERSAL', 'AUTHENTICATION_BYPASS', 'SESSION_HIJACKING', 'SUBDOMAIN_ENUMERATION', 'API_SECURITY', 'OPEN_REDIRECT', 'CLICKJACKING', 'FILE_UPLOAD_VULNERABILITY', 'CSP_BYPASS', 'BROKEN_ACCESS_CONTROL', 'INSECURE_DESERIALIZATION', 'BROKEN_AUTHENTICATION', 'SENSITIVE_DATA_EXPOSURE', 'WEAK_SESSION_MANAGEMENT', 'PATH_PARAMETER_ATTACKS', 'HTTP_REQUEST_SMUGGLING', 'BUSINESS_LOGIC_BUGS', 'HOST_HEADER_INJECTION', 'HTTP_RESPONSE_SPLITTING', 'CACHE_POISONING', 'DOM_BASED_XSS', 'CORS_MISCONFIGURATION', 'IDOR', 'HTML_INJECTION', 'XML_EXTERNAL_ENTITY', 'HIDDEN_PARAMETER_DISCOVERY', 'INPUT_VALIDATION_BUGS', 'CROSS_ORIGIN_SCRIPTING', 'TEMPLATE_INJECTION', 'MISCONFIGURED_SECURITY_HEADERS', 'RATE_LIMITING_BYPASS', 'PASSWORD_RESET_POISONING', 'WEBSOCKET_SECURITY', 'WEAK_ENCRYPTION', 'DEPENDENCY_VULNERABILITIES', 'JAVASCRIPT_PROTOTYPE_POLLUTION');

-- CreateEnum
CREATE TYPE "ChallengeStatus" AS ENUM ('ON_GOING', 'DONE');

-- CreateTable
CREATE TABLE "Challenge" (
    "id" SERIAL NOT NULL,
    "creatorId" UUID NOT NULL,
    "winnerId" UUID,
    "name" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "targetLink" TEXT NOT NULL,
    "prize" INTEGER NOT NULL,
    "methods" "WebHackingMethod"[],
    "status" "ChallengeStatus" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Challenge_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "Challenge" ADD CONSTRAINT "Challenge_creatorId_fkey" FOREIGN KEY ("creatorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Challenge" ADD CONSTRAINT "Challenge_winnerId_fkey" FOREIGN KEY ("winnerId") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
